### ISSUE TITLE
output results to file

### ISSUE THREAD

**Issue by talkncloud** [talkncloud/tnc-cup-client#35]
some users may want to save the output of the results to file using the client e.g. results.out 

need to explore this a little more and see if this something users want to do.

**Comment by talkncloud** [comment]
expanding on this.

new parameters:
- -j produces json to stdout
- -o produces git friendly file to track tnc-cup changes with

the default behaviour is to product the tabular output to stdout, only when the above params are used should it change the behaviour. this will be useful for ci/cd to use the -o and compare for the commits etc. 

the -o parameter switch needs investigation on the format e.g. can the table format be used for the file and doe that make sense when looking at git in the browser to review and approve.

**Comment by tientham** [comment]
-j is ready for testing: 
commit: c7d79bc699066b5a06a8e3083d19fb28322e9acf

**Comment by talkncloud** [comment]
> -j is ready for testing:
> commit: [c7d79bc](https://github.com/talkncloud/tnc-cup-client/commit/c7d79bc699066b5a06a8e3083d19fb28322e9acf)

hey mate, looks good. will issue a PR.

We'll split out the the -o option as discussed to do some more planning inline with that upcoming feature work.
