### ISSUE TITLE
will the backend be open sourced?

### ISSUE THREAD

**Issue by networkpadawan** [talkncloud/tnc-cup-client#66]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by talkncloud** [comment]
Hi,

Thanks for reaching out.

While this has been discussed on and off there are no immediate plans to open-source the backend. If you have additional requirements please us know and we'll get them done. 

Thanks.
